### ISSUE TITLE
hi~

### ISSUE THREAD

**Issue by yihong0618** [William-Wang1988/gitblog#4]
![image](https://user-images.githubusercontent.com/15976103/91700659-d0e62c00-eba8-11ea-91ae-e7064c8ec996.png)

你这里gitblog是个变量需要在[secret](https://github.com/yihong0618/gitblog/settings/secrets)里设置的

这个是我的变量名，你需要改成你的就可以了
![image](https://user-images.githubusercontent.com/15976103/91700793-f96e2600-eba8-11ea-8cc7-e835da63cedf.png)

**Comment by yihong0618** [comment]
这个是你需要生成的，把需要的地方点上就可以了。

**Comment by yihong0618** [comment]
token在[这里](https://github.com/settings/tokens) 点击 generate new token生成。
![image](https://user-images.githubusercontent.com/15976103/91701335-b791af80-eba9-11ea-893a-10c4fa55418a.png)

**Comment by William-Wang1988** [comment]
你好，这个token的范围需要选什么？
![image](https://user-images.githubusercontent.com/53826012/91701770-561e1080-ebaa-11ea-8467-5a586d22f46b.png)

**Comment by yihong0618** [comment]
@William-Wang1988 
我是全点上了，正常点需要的就行。比如package这里不需要。
如果你不确定是干嘛的，建议点上。

**Comment by yihong0618** [comment]
@William-Wang1988 

不要忘了 secret.（你的secret名）
比如我的secret 名叫G_T

![image](https://user-images.githubusercontent.com/15976103/91702254-09870500-ebab-11ea-9df8-01abdf430e24.png)

**Comment by yihong0618** [comment]
![image](https://user-images.githubusercontent.com/15976103/91702333-2ae7f100-ebab-11ea-96d5-7e3585fdfe66.png)

secrets.GITBLOG（和你设置的名一致）

**Comment by William-Wang1988** [comment]
哎呀，我忘了😥

**Comment by William-Wang1988** [comment]
wow, it finally work!!!🎉，非常感谢🙇‍

**Comment by yihong0618** [comment]
> wow, it finally work!!!🎉，非常感谢🙇‍

客气了，有问题可以开issue at 我。
